//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garcom.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensagensRetorno {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensRetorno() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Garcom.Core.MensagensRetorno", typeof(MensagensRetorno).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código rápido já cadastrado..
        /// </summary>
        internal static string CodigoRapidoJaCadastrado {
            get {
                return ResourceManager.GetString("CodigoRapidoJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de senha diferente da senha informada..
        /// </summary>
        internal static string ConfirmacaoSenhaDiferente {
            get {
                return ResourceManager.GetString("ConfirmacaoSenhaDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de produto já cadastrado..
        /// </summary>
        internal static string GrupoProdutoJaCadastrado {
            get {
                return ResourceManager.GetString("GrupoProdutoJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de produto não cadastrado..
        /// </summary>
        internal static string GrupoProdutoNaoCadastrado {
            get {
                return ResourceManager.GetString("GrupoProdutoNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório informar se o ingrediente é opcional ou adicional..
        /// </summary>
        internal static string InformarIngredienteOpcionalOuAdic {
            get {
                return ResourceManager.GetString("InformarIngredienteOpcionalOuAdic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrediente já cadastrado..
        /// </summary>
        internal static string IngredienteJaCadastrado {
            get {
                return ResourceManager.GetString("IngredienteJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrediente não cadastrado..
        /// </summary>
        internal static string IngredienteNaoCadastrado {
            get {
                return ResourceManager.GetString("IngredienteNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesa já cadastrada..
        /// </summary>
        internal static string MesaJaCadastrado {
            get {
                return ResourceManager.GetString("MesaJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesa não cadastrada..
        /// </summary>
        internal static string MesaNaoCadastrado {
            get {
                return ResourceManager.GetString("MesaNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto já cadastrado..
        /// </summary>
        internal static string ProdutoJaCadastrado {
            get {
                return ResourceManager.GetString("ProdutoJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto não cadastrado..
        /// </summary>
        internal static string ProdutoNaoCadastrado {
            get {
                return ResourceManager.GetString("ProdutoNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha está incorreta..
        /// </summary>
        internal static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho já cadastrado..
        /// </summary>
        internal static string TamanhoJaCadastrado {
            get {
                return ResourceManager.GetString("TamanhoJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho não cadastrado..
        /// </summary>
        internal static string TamanhoNaoCadastrado {
            get {
                return ResourceManager.GetString("TamanhoNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse usuário está inativo..
        /// </summary>
        internal static string UsuarioInativo {
            get {
                return ResourceManager.GetString("UsuarioInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontrei esse usuário..
        /// </summary>
        internal static string UsuarioInvalido {
            get {
                return ResourceManager.GetString("UsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuário já está sendo utilizado..
        /// </summary>
        internal static string UsuarioJaCadastrado {
            get {
                return ResourceManager.GetString("UsuarioJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não cadastrado..
        /// </summary>
        internal static string UsuarioNaoCadastrado {
            get {
                return ResourceManager.GetString("UsuarioNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do produto não foi informado..
        /// </summary>
        internal static string ValorProdutoNaoInformado {
            get {
                return ResourceManager.GetString("ValorProdutoNaoInformado", resourceCulture);
            }
        }
    }
}
